services:
  db:
    profiles:
      - nightfall
      - greenland
    image: postgres:18-alpine
    container_name: auth-manager-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_manager
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth_manager"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - auth-manager-network

  keycloak:
    profiles:
      - nightfall
      - greenland
    image: quay.io/keycloak/keycloak:26.4
    container_name: auth-manager-keycloak
    platform: linux/amd64
    command: start --import-realm --spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false -Dkeycloak.profile.feature.admin_fine_grained_authz=enabled
    post_start:
      - command: /opt/keycloak/data/import/scripts/kc-post-start-hook.sh
        user: root
        privileged: true
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak
      KC_HOSTNAME: localhost
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_SSL_REQUIRED=none: none
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME_STRICT: false
      KC_HTTP_PORT: "8081"
      KC_PROXY_HEADERS: xforwarded
      KC_METRICS_ENABLED: true
      KC_EVENT_METRICS_USER_ENABLED: false
      KC_HTTP_METRICS_HISTOGRAMS_ENABLED: false
      KC_CACHE_METRICS_HISTOGRAMS_ENABLED: false
      JAVA_OPTS_APPEND: "-Xms512m -Xmx2g"
      PROXY_ADDRESS_FORWARDING: true
      KC_HTTP_RELATIVE_PATH: "/auth"
    volumes:
      - ./deployment/shared/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
      - ./scripts/kc-post-start-hook.sh:/opt/keycloak/data/import/scripts/kc-post-start-hook.sh
    ports:
      - 8081:8081
      - 9000:9000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - auth-manager-network

  auth-manager:
    profiles:
      - nightfall
    image: "${SERVICE_NAME}:${SERVICE_TAG}"
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - APP_NAME
      - APP_VERSION
      - COMMIT_SHA
      tags:
      - "${SERVICE_NAME}:${SERVICE_TAG_LABEL}"
      - "${SERVICE_NAME}:${SERVICE_TAG}"
    container_name: auth-manager-service
    restart: unless-stopped
    env_file: .env.docker
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync+restart
          path: ../app
          target: /code/app
        - action: sync+restart
          path: ../scripts/entrypoint.sh
          target: /code/entrypoint.sh
        - action: rebuild
          path: uv.lock
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    networks:
      - auth-manager-network

volumes:
  postgres_data:
    driver: local

networks:
  auth-manager-network:
    driver: bridge
    name: auth-manager-network
