"""rename metadata

Revision ID: 25b672166d01
Revises: e42849e026b2
Create Date: 2025-10-24 23:13:26.439548

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "25b672166d01"
down_revision: Union[str, Sequence[str], None] = "e42849e026b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "auth_vault",
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.drop_column("auth_vault", "metadata")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "auth_vault",
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("auth_vault", "attributes")
    # ### end Alembic commands ###
