"""init

Revision ID: e42849e026b2
Revises:
Create Date: 2025-10-24 17:59:17.685129

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e42849e026b2"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_vault",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "token_type", sa.Enum("OFFLINE", "REFRESH", name="auth_token_type"), nullable=False
        ),
        sa.Column("encrypted_token", sa.Text(), nullable=True),
        sa.Column("iv", sa.Text(), nullable=True),
        sa.Column("token_hash", sa.Text(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("session_state_id", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_vault")),
    )
    op.create_index(
        "auth_vault_session_state_token_type_idx",
        "auth_vault",
        ["session_state_id", "token_type"],
        unique=False,
    )
    op.create_index(
        "auth_vault_user_id_token_type_idx", "auth_vault", ["user_id", "token_type"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("auth_vault_user_id_token_type_idx", table_name="auth_vault")
    op.drop_index("auth_vault_session_state_token_type_idx", table_name="auth_vault")
    op.drop_table("auth_vault")
    # ### end Alembic commands ###
